# Generated by Django 3.0.5 on 2020-05-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200509_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rpc_sending_time',
            field=models.DateTimeField(null=True),
        ),
    ]
