# Generated by Django 3.0.5 on 2020-05-27 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200509_0016'),
    ]

    operations = [
        migrations.RunSQL(
            ('CREATE FULLTEXT INDEX user_fulltext_index ON user_user (username, email, organization)',),
            ('DROP INDEX user_fulltext_index on user_user',)
        )
    ]
